
import AdaLean.sum_neg_cancel
import AdaLean.sum_eq_two
import AdaLean.two_mod_two_pow
import AdaLean.two_pow_eq_two_pow_sub_add
import AdaLean.mul_two_div_mul
import AdaLean.ico_choose_eq_two_pow
import AdaLean.inv_2m_add
import AdaLean.congr_Ico_succ
import AdaLean.range_sub_choose_add_sum
import AdaLean.choose_mul_pow_eq_mul
import AdaLean.sum_choose_eq_Ico
import AdaLean.Ico_odd_div_choose
import AdaLean.Ico_choose_add_eq_mul_pred
import AdaLean.two_mul_sum
import AdaLean.sum_add_eq_add
import AdaLean.sum_mul_congr
import AdaLean.sum_neg_comm
import AdaLean.Ico_succ_mul_choose_eq
import AdaLean.add_two_subY
import AdaLean.pow_neg_succ_succ
import AdaLean.sub_two_add_one
import AdaLean.Ico_choose
import AdaLean.mul_mul_div_succ_mul_choose
import AdaLean.neg_pow_div_choose
import AdaLean.range_choose_eq_ico_choose
import AdaLean.add_neg_div
import AdaLean.choose_add_div_distrib
import AdaLean.two_pow_div_two
import AdaLean.two_m_div_add
import AdaLean.lt_eq_le_sub
import AdaLean.sum_add_eq_two_pow
import AdaLean.sum_choose_sub_eq_add
import AdaLean.choose_mul_add_pow
import AdaLean.pow_eq_sub_one_mul
import AdaLean.Ico_simpn
import AdaLean.two_even_congr
import AdaLean.add_two_sub
import AdaLean.mul_sum_choose
import AdaLean.sum_neg_pow_mul_mul
import AdaLean.choose_mul_eq_mul_sub
import AdaLean.sum_neg_pow_mul_eq_sum_distrib
import AdaLean.mul_two_pow_add_eq_mul_pow
import AdaLean.two_mul_succ_sub
import AdaLean.sum_choose_symm
import AdaLean.sum_neg_pow_mul_add
import AdaLean.ico_mul_choose_sub
import AdaLean.choose_mul_eq_mul_sub'
import AdaLean.mul_mul_div_succ_mul_choose_eq_succ
import AdaLean.two_pow_eq_range_add_ico
import AdaLean.sub_add_eq_add
import AdaLean.choose_eq_choose_add
import AdaLean.sum_mul_choose_eq_mul_two_pow_sub
import AdaLean.two_mul_div_add
import AdaLean.sum_choose_sub_eq_add_sub
import AdaLean.add_div_two
import AdaLean.choose_sub_sub
import AdaLean.bot_sum_mul_congr
import AdaLean.range_eq_ico_mul_choose
import AdaLean.sum_two_pow_mul_choose
import AdaLean.sum_sub_sum_add
import AdaLean.h_pow_zero_mul_add
import AdaLean.sum_neg_pow_mul_mul_choose
import AdaLean.sum_neg_pow_mul_distrib
import AdaLean.add_div_two_eq_distrib
import AdaLean.sum_neg_pow_div_congr
import AdaLean.sum_assoc
import AdaLean.sum_neg_assoc
import AdaLean.pow_zero_mul_add_sum
import AdaLean.mul_same
import AdaLean.range_mul_add
import AdaLean.choose_eq_choose_add_nk
import AdaLean.Ico_mul_add
import AdaLean.ico_succ
import AdaLean.sum_mul_add_distrib
import AdaLean.Ico_div
import AdaLean.mul_choose_two_pow
import AdaLean.range_sub_choose
import AdaLean.mul_choose_eq_mul_choose
import AdaLean.range_sub_add_cancel
import AdaLean.ico_two_pow
import AdaLean.icc_eq_ico
import AdaLean.sum_add_div_two
import AdaLean.choose_eq_choose_sub_add
import AdaLean.Ico_choose_range_choose
import AdaLean.sum_mul_choose_eq_mul_two_pow
import AdaLean.mul_add_mul_eq_mul
import AdaLean.Transit_item
import AdaLean.choose_eq_choose_sub_add_nk
import AdaLean.choose_mul_eq_choose_mul
import AdaLean.neg_pow_mul_mul_mul
import AdaLean.choose_sub_eq_choose_sub_add
import AdaLean.two_mul_add_sub
import AdaLean.mul_choose_sub
import AdaLean.choose_le_sum
import AdaLean.neg_pow_choose
import AdaLean.neg_pow_cancel
import AdaLean.odd_choose_sum
import AdaLean.sum_choose_eq
import AdaLean.neg_pow_mul_choose_mul_eq_mul_sub
import Lean4Repl
import Mathlib.Data.Nat.Choose.Sum
import Mathlib.Data.Real.Basic
import Mathlib.Data.Finset.LocallyFinite
import Mathlib.Algebra.Algebra.Basic
import Mathlib.Algebra.Order.Floor
import Mathlib.Algebra.Associated
import Mathlib.Algebra.BigOperators.Basic
import Mathlib.Algebra.BigOperators.Order
import Mathlib.Algebra.BigOperators.Pi
import Mathlib.Algebra.GeomSum
import Mathlib.Algebra.Group.Basic
import Mathlib.Algebra.Group.Commute.Basic
import Mathlib.Algebra.Group.Defs
import Mathlib.Algebra.GroupPower.Basic
import Mathlib.Algebra.GroupPower.Identities
import Mathlib.Algebra.Order.Floor
import Mathlib.Algebra.QuadraticDiscriminant
import Mathlib.Algebra.Ring.Basic
import Mathlib.Analysis.Asymptotics.AsymptoticEquivalent
import Mathlib.Analysis.NormedSpace.Basic
import Mathlib.Analysis.SpecialFunctions.Log.Basic
import Mathlib.Analysis.SpecialFunctions.Log.Base
import Mathlib.Combinatorics.SimpleGraph.Basic
import Mathlib.Data.Complex.Basic
import Mathlib.Data.Complex.Exponential
import Mathlib.Data.Finset.Basic
import Mathlib.Data.Fintype.Card
import Mathlib.Data.Int.Basic
import Mathlib.Data.Int.GCD
import Mathlib.Data.Int.ModEq
import Mathlib.Data.Int.Parity
import Mathlib.Data.List.Intervals
import Mathlib.Data.List.Palindrome
import Mathlib.Data.Multiset.Basic
import Mathlib.Data.Nat.Basic
import Mathlib.Data.Nat.Choose.Basic
import Mathlib.Data.Nat.Digits
import Mathlib.Data.Nat.Factorial.Basic
import Mathlib.Data.Nat.ModEq
import Mathlib.Data.Nat.Multiplicity
import Mathlib.Data.Nat.Parity
import Mathlib.Data.Nat.Prime
import Mathlib.Data.PNat.Basic
import Mathlib.Data.PNat.Prime
import Mathlib.Data.Polynomial.Basic
import Mathlib.Data.Polynomial.Eval
import Mathlib.Data.Real.Basic
import Mathlib.Data.Real.Irrational
import Mathlib.Data.Real.NNReal
import Mathlib.Data.Real.Sqrt
import Mathlib.Data.Set.Finite
import Mathlib.Data.Sym.Sym2
import Mathlib.Data.ZMod.Basic
import Mathlib.Dynamics.FixedPoints.Basic
import Mathlib.LinearAlgebra.AffineSpace.AffineMap
import Mathlib.LinearAlgebra.AffineSpace.Independent
import Mathlib.LinearAlgebra.AffineSpace.Ordered
import Mathlib.LinearAlgebra.FiniteDimensional
import Mathlib.Logic.Equiv.Basic
import Mathlib.Order.Filter.Basic
import Mathlib.Order.LocallyFinite
import Mathlib.Order.WellFounded
import Mathlib.Topology.Basic
import Mathlib.Topology.Instances.NNReal
import Aesop
set_option trace.aesop true
set_option trace.aesop.proof true
set_option maxHeartbeats 999999999999999999999999
open Nat Real Rat BigOperators Function

variable [CommGroup G] {{a b c d : G }}

theorem div_eq_of_eq_mul'0 {a b c : G} (h : a = b * c) : a / b = c := by lean_repl sorry
